spring:
  application:
    name: backend-pedidos
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true